services:
  postgres:
    image: postgres:latest
    container_name: job-board-postgres
    environment:
      POSTGRES_DB: ${PG_DB:-jobboard}
      POSTGRES_USER: ${PG_USER:-jobboard_user}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-jobboard_password}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${PG_USER:-jobboard_user} -d ${PG_DB:-jobboard}',
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    container_name: job-board-backend
    user: '${UID:-1000}:${GID:-1000}'
    environment:
      PORT: ${PORT:-3000}
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL:-postgresql://jobboard_user:jobboard_password@postgres:5432/jobboard}
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    command: bun run dev

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    container_name: job-board-frontend
    user: '${UID:-1000}:${GID:-1000}'
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:${PORT:-3000}
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend
    command: bun run dev

volumes:
  postgres_data:
