version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: job-board-db
    environment:
      POSTGRES_DB: jobboard
      POSTGRES_USER: jobboard_user
      POSTGRES_PASSWORD: jobboard_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jobboard_user -d jobboard"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: job-board-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@jobboard.dev
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: job-board-backend
    environment:
      PORT: 3000
      NODE_ENV: development
      DATABASE_URL: postgresql://jobboard_user:jobboard_password@db:5432/jobboard
    ports:
      - "3000:3000"
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    command: bun run dev

volumes:
  postgres_data:
  pgadmin_data: